POST https://aurion.junia.com/login
Content-Type: application/x-www-form-urlencoded
Connection: keep-alive

username=USERNAME&password=PASSWORD&j_idt28=

# #

# GET https://aurion.junia.com/
# Connection: keep-alive
# Cookie: JSESSIONID=4DC3172EC3D8BF18199AF33D242D576F

